apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: ais-fb-dev
spec:
  type: ClusterIP
  selector:
    app: ais-fb-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
